const MAIN_SCREEN_APP_BAR_TITLE = 'Discover';
const MAIN_SCRREN_BEST_POPULAR_MOVIES_AND_SERIALS ="BEST POPULAR MOVIES AND SERIALS";

const MAIN_SCREEN_SEE_MORE = "SEE MORE";
const MAIN_SCREEN_CHECK_MOVIEW_SHOWTIMES = "Check Movie\nShowtimes";
const SHOW_CASES_TITLE = "SHOWCASES";
const SHOW_CASES_SEE_MORE = "MORE SHOWCASES";
const BEST_ACTOR_TITLE = "BEST ACTORS";
const ACTOR_TITLE =  "ACTORS";
const BEST_ACTOR_SEE_MORE = "MORE ACTORS";
const CREATOR_TITLE = "CREATORS";

const MOVIE_DETAIL_SCREEN_ACTORS_TITLE =  "ACTORS";
const MOVIE_DETAIL_SCREEN_CREATORS_TITLE = "CREATORS";
const MOVIE_DETAIL_SCREEN_CREATORS_SEE_MORE = "MORE CREATORS";
const MOVIE_DETAIL_STORYLINE_TITLE ="STORYLINE";